### PR TITLE
fix: disable region check for Azure CloudEnvironment

### LINKED ISSUE #66: [bug][cloudenvironment] the region argument for Azure should be a resource group name, and so cannot validate it

### PR DESCRIPTION
**Pull request by jiangpengcheng**
fix #66

Azure needs to use ResourceGroup name in the region parameter, so cannot validate it

### CODE REVIEW

File: cloud/resource_cloud_environment.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func resourceCloudEnvironment() *schema.Resource {
 				Type:         schema.TypeString,
 				Required:     true,
 				Description:  descriptions["region"],
-				ValidateFunc: validateRegion,
+				ValidateFunc: validateNotBlank,
```
Comment (maxsxu) [inline cloud/resource_cloud_environment.go:93]: But it's useful for AWS and GCP, can we create separate rule for Azure?

Comment (maxsxu) [reply cloud/resource_cloud_environment.go:93]: I've updated this PR to add separate validation rules: https://github.com/streamnative/terraform-provider-streamnative/pull/69/files#diff-c02472e6df317b435706b287c76b320eea0b27f53a2bc8c447058fcc2be79cf6R227

**Review by maxsxu — APPROVED** [review]
